name: mynotesapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_analytics: ^12.0.4
  test: ^1.26.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  share_plus: ^12.0.1
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  google_sign_in: ^6.2.1
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  web: ^1.1.1
  flutter_local_notifications: ^17.2.2
  image_picker: ^1.1.2 
  camera: ^0.11.0+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/icon.png
    - assets/icon/google_logo.png
